language: r
sudo: false
cache: packages
dist: trusty

latex: true


env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
           # - g++-7
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        # - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = clang++-6.0 -fPIC -flto=2" >> ~/.R/R_Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

  ##- echo "CXX14FLAGS = `R CMD config CXXFLAGS` -pedantic -g0 -fPIC" >> ~/.R/R_Makevars
  # - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  # - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check DCPO*tar.gz

after_script:
  - tar -ztvf DCPO_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat DCPO.Rcheck/00*
