#' Estimate Dynamic Comparative Public Opinion
#'
#' \code{dcpo} uses diverse survey data to estimate public opinion across countries and over time.
#'
#' @param x a data frame of survey items and marginals generated by \code{DCPOtools::dcpo_setup}
#' @param chime play chime when complete?
#
#' @details \code{dcpo}, when passed a data frame \code{x} of survey marginals created by \code{dcpo_setup}, estimates a latent variable of public opinion.
#'
#' @return a stanfit object
#'
#' @import rstan
#' @importFrom beepr beep
#'
#' @export

dcpo <- function(x,
                 chime = TRUE,
                 ...) {

  dcpo_model <- stanmodels$dcpo
  stan_args <- list(object = dcpo_model,
                    data = dcpo_data,
                    ...)
  if (!length(stan_args$control)) {
    stan_args$control <- list(max_treedepth = 14)
  }
  if (!length(stan_args$seed)) {
    stan_args$seed <- 324
  }
  if (!length(stan_args$chains)) {
    stan_args$chains <- 3
  }
  if (!length(stan_args$cores)) {
    stan_args$cores <- min(stan_args$chains, parallel::detectCores()/2)
  }
  out1 <- do.call(rstan::sampling, stan_args)

  # Chime
  if(chime) {
    try(beep())
  }

  return(out1)
}
