#' Select Countries with Observations in a Minimum Number of Distinct Years
#'
#' \code{dcpo} uses diverse survey data to estimate public opinion across countries and over time.
#'
#' @param x a data frame of survey items and marginals generated by \code{dcpo_setup}
#' @param min_yrs the minimum number of distinct years needed for a country included x to be retained
#
#' @details \code{dcpo}, when passed a data frame \code{x} of survey marginals created by \code{dcpo_setup}, estimates a latent variable of public opinion.
#'
#' If a data frame of independent variables including observations for all countries that appear in \code{x} for each year in the time period from the first to last year to appear in \code{x} is passed to the argument \code{iv}, \code{dcpo} will also estimate coefficients for these predictors.
#'
#' @return a data frame
#'
#' @importFrom dplyr "%>%" filter mutate arrange group_by ungroup
#'

#' @export
with_min_yrs <- function(x, min_yrs) {
  if (!is.na(min_yrs)) {
    x <- x %>%
      filter(year_obs >= min_yrs) %>%
      mutate(ccode = as.integer(factor(ccode)),
             tcode = as.integer(year - min(year) + 1),
             qcode = as.numeric(factor(variable, levels = unique(variable))),
             rcode = as.numeric(factor(variable_cp, levels = unique(variable_cp))),
             ktcode = (ccode-1)*max(tcode)+tcode) %>%
      arrange(ccode, tcode, qcode, rcode) %>%
      group_by(ccode) %>%
      mutate(tq = length(unique(paste(tcode, qcode))),
             year_obs = length(unique(tcode))) %>%
      ungroup()
  }
  return(x)
}
